steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/demoweb:$TAG_NAME', '.']
  id: 'build-gcr'
- name: 'gcr.io/living-bio/workspace'
  args: ['bash','/script/sync-ali.sh','demoweb','$TAG_NAME']
  id: 'build-ali'
images: ['asia.gcr.io/$PROJECT_ID/demoweb:$TAG_NAME']
