steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/demoweb:$TAG_NAME', '.']
  id: 'build'
- name: 'ubuntu'
  args: ['bash', './test.sh']
images: ['gcr.io/$PROJECT_ID/demoweb:$TAG_NAME','registry-cn.gliavideo.cn/test/demoweb:$TAG_NAME']
